---
# Installation des packages qui seront installés par defaut dans tous les serveurs
- name: Installation des | fish vim git
  apt:
    name: 
      - fish
      - vim
      - git
    state: present

- name: Installation de | vim plug
  command: curl -fLo ~/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  creates: ~/.vimrc
- name: Installation de | vim configuration
  get_url:
    url: https://github.com/Grafikart/dotfiles/tree/master/config/vim
    dest: ~/.vimrc
    
- name: "Installation de | vim configuration pour l'utilisateur {{ user}}"
  get_url:
    url: https://github.com/Grafikart/dotfiles/tree/master/config/vim
    dest: /home/{{ user }}/.vimrc
    group: "{{ user }}"
    owner: " {{ user }}"
- name: Installation de | vim plug
  command: curl -fLo ~/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  become_user: "{{ user }}"
  become: true
  creates: /home/{{ user }}/.vimrc
  


